import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {ArrowUp,ArrowUpRight,BookOpen,Check,ChevronRight,CircleHelp,Code2,Download,FileText,LogOut,Menu,MessageSquare,PanelRightClose,Plus,Search,ShieldCheck,Sparkles,Square,Trash2,Users,X} from 'lucide-react';
import {accessToken,api,clearAccessToken,consumeSSE,setAccessToken,type AdminUser,type Artifact,type Health,type Message,type Session,type Source,type User} from './api';
import {safeDocument} from './safety';
import './styles.css';
const starters=[{tag:'FIND YOUR FOCUS',q:'How should an early-stage team measure product-market fit?',icon:Search},{tag:'BUILD A GROWTH LOOP',q:'What makes a product-led growth strategy work?',icon:Sparkles},{tag:'KEEP PEOPLE COMING BACK',q:'How can we improve retention before investing in acquisition?',icon:BookOpen}];
function Markdown({text}:{text:string}){return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{img:props=><span>[Image omitted: {props.alt||"external image"}]</span>,a:props=><a {...props} target="_blank" rel="noreferrer noopener"/>}}>{text}</ReactMarkdown></div>}
function SourceCards({sources}:{sources:Source[]}){return <div className="sources">{sources.map(s=><details key={s.id}><summary><span className="source-number">{s.id}</span><span>{s.guest}<small>{s.timestamp_ref||'Transcript excerpt'}</small></span><ChevronRight size={14}/></summary><p>{s.content}</p><a href={/^https?:\/\//.test(s.source_url)?s.source_url:undefined} target="_blank" rel="noreferrer">{s.title} <ArrowUpRight size={12}/></a></details>)}</div>}
function Workspace({user,onLogout}:{user:User;onLogout:()=>void}){
 const [sessions,setSessions]=useState<Session[]>([]),[active,setActive]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]);
 const [artifacts,setArtifacts]=useState<Artifact[]>([]),[artifact,setArtifact]=useState<Artifact|null>(null),[view,setView]=useState<'preview'|'source'>('preview');
 const [health,setHealth]=useState<Health|null>(null),[input,setInput]=useState(''),[provider,setProvider]=useState('gemini'),[mode,setMode]=useState('answer');
 const [busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[warning,setWarning]=useState(''),[sidebar,setSidebar]=useState(false),[system,setSystem]=useState(false),[help,setHelp]=useState(false);
 const abort=useRef<AbortController|null>(null),end=useRef<HTMLDivElement>(null),scroll=useRef<HTMLDivElement>(null),follow=useRef(true),inputRef=useRef<HTMLTextAreaElement>(null);
 const refresh=()=>{api<Session[]>('/sessions').then(setSessions).catch(()=>{});api<Health>('/health').then(setHealth).catch(()=>setHealth(null));};
 useEffect(()=>{refresh();const saved=localStorage.getItem('lenny-session');if(saved)void select(saved);const t=setInterval(refresh,30000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(follow.current)end.current?.scrollIntoView({behavior:'instant'});},[messages,status]);
 async function select(id:string){if(busy)return;try{const data=await api<{messages:Message[];artifacts:Artifact[]}>('/sessions/'+id);setActive(id);localStorage.setItem('lenny-session',id);setMessages(data.messages);setArtifacts(data.artifacts);setArtifact(data.artifacts.at(-1)||null);setError('');setWarning('');setSidebar(false)}catch(e){setError((e as Error).message)}}
 function newChat(){if(busy)return;setActive(null);localStorage.removeItem('lenny-session');setMessages([]);setArtifacts([]);setArtifact(null);setInput('');setError('');setWarning('');setSidebar(false);inputRef.current?.focus()}
 async function send(question=input){
  if(busy||!question.trim())return;
  setBusy(true);setError('');setWarning('');setStatus('Starting your request');setInput('');follow.current=true;
  let sid=active;let completed=false;const temp='stream-'+Date.now();
  abort.current=new AbortController();
  try{
   if(!sid){const s=await api<Session>('/sessions',{method:'POST',body:JSON.stringify({title:'New conversation',user_metadata:{client:'local-web'}})});sid=s.id;setActive(s.id);localStorage.setItem('lenny-session',s.id)}
   setMessages(m=>[...m,{id:'user-'+Date.now(),role:'user',content:question,sources:[]},{id:temp,role:'assistant',content:'',sources:[],provider,mode}]);
   const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken()}`},signal:abort.current.signal,body:JSON.stringify({session_id:sid,message:question,provider,mode})});
   if(!res.ok){const data=await res.json();throw new Error(data.error?.message||'Request failed')}
   if(!res.body)throw new Error('Streaming is unavailable');
   await consumeSSE(res.body,e=>{
    if(e.type==='status')setStatus(e.content);
    if(e.type==='sources')setMessages(m=>m.map(x=>x.id===temp?{...x,sources:e.sources}:x));
    if(e.type==='replace')setMessages(m=>m.map(x=>x.id===temp?{...x,content:e.content}:x));
    if(e.type==='token')setMessages(m=>m.map(x=>x.id===temp?{...x,content:x.content+e.content}:x));
    if(e.type==='warning')setWarning(e.content);
    if(e.type==='artifact'){setArtifacts(a=>[...a,e.artifact]);setArtifact(e.artifact);setView('preview')}
    if(e.type==='error')throw new Error(e.content+(e.request_id?' Request ID: '+e.request_id:''));
    if(e.type==='done'){completed=true;setStatus('Complete');setMessages(m=>m.map(x=>x.id===temp?{...x,id:e.message_id,status:'complete'}:x))}
   });
   if(!completed)throw new Error('The connection ended before the response was saved. Retry your request.');
  }catch(e){const msg=(e as Error).name==='AbortError'?'Generation stopped. Partial text is not a completed answer.':(e as Error).message;setError(msg);setMessages(m=>m.map(x=>x.id===temp?{...x,status:'failed'}:x));}
  finally{setBusy(false);setStatus('');abort.current=null;refresh()}
 }
 async function removeSession(id:string){
  if(busy||!window.confirm('Delete this conversation and all of its messages? This cannot be undone.'))return;
  try{await api<void>('/sessions/'+id,{method:'DELETE'});if(active===id)newChat();refresh()}catch(e){setError((e as Error).message)}
 }
 function download(){if(!artifact)return;const content=artifact.artifact_type==='html'?safeDocument(artifact.content):artifact.content;const url=URL.createObjectURL(new Blob([content],{type:artifact.artifact_type==='html'?'text/html':'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='lenny-'+artifact.id.slice(0,8)+(artifact.artifact_type==='html'?'.html':'.md');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const words=artifact?.content.trim().split(/\s+/).length||0;
 return <div className={'app '+(artifact?'with-artifact':'')}>
  {sidebar&&<button className="overlay" aria-label="Close conversations" onClick={()=>setSidebar(false)}/>}
  <aside className={'sidebar '+(sidebar?'open':'')}>
   <a className="brand" href="#" onClick={e=>{e.preventDefault();newChat()}}><span className="brand-mark">L<span>✳</span></span><span>Lenny<span className="brand-sub">GROWTH ASSISTANT</span></span></a>
   <button className="new-chat" onClick={newChat} disabled={busy}><Plus size={17}/> New conversation <span>↗</span></button>
   <div className="sidebar-label">YOUR WORKSPACE</div><div className="session-list">{sessions.length===0?<p className="empty-sessions">Your conversations will live here.</p>:sessions.map(s=><div key={s.id} className={'session-row '+(s.id===active?'selected':'')}><button className="session" onClick={()=>select(s.id)} disabled={busy}><MessageSquare size={15}/><span>{s.title}</span></button><button className="delete-session" aria-label={'Delete '+s.title} title="Delete conversation" onClick={()=>void removeSession(s.id)} disabled={busy}><Trash2 size={14}/></button></div>)}</div>
   <div className="archive-note"><BookOpen size={18}/><div>Wisdom, with receipts.<p>Every answer starts with the archive.</p></div></div>
   <button className="system-button" onClick={()=>{setSystem(!system);refresh()}}><span className={'dot '+(health?.ready?'good':'')}/><span>{health?.ready?'Workspace ready':'Check system status'}</span><ChevronRight size={14}/></button>
   <div className="profile"><span>{user.name.slice(0,1).toUpperCase()}</span><div>{user.name}<small>{user.is_admin?'Master administrator':'Signed-in workspace'}</small></div><button className="logout" title="Sign out" onClick={onLogout}><LogOut size={15}/></button></div>
  </aside>
  <main className="main">
   <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open conversations" onClick={()=>setSidebar(true)}><Menu size={20}/></button><span>Workspace</span><ChevronRight size={13}/><strong>{messages.length?'Conversation':'New conversation'}</strong></div><div className="provider"><span className="dot good"/><select aria-label="Model provider" value={provider} disabled={busy} onChange={e=>setProvider(e.target.value)}><option value="gemini">Gemini · Cloud</option><option value="ollama">Ollama · Local</option><option value="anthropic">Claude · Cloud</option></select></div><button className="help-button" onClick={()=>setHelp(!help)}><CircleHelp size={14}/> Help</button>{user.is_admin&&<AdminPanel/>}</header>
   {help&&<section className="help-panel"><div><strong>Need help?</strong><button className="icon-button" aria-label="Close help" onClick={()=>setHelp(false)}><X size={16}/></button></div><p>If you encounter an issue with your account, conversations, or research workspace, contact the administrator.</p>{health?.admin_contact?<a href={'mailto:'+health.admin_contact}>{health.admin_contact}</a>:<p>Administrator contact is not configured yet.</p>}</section>}
   {system&&<section className="system-panel"><div><strong>System status</strong><button className="icon-button" aria-label="Close system status" onClick={()=>setSystem(false)}><X size={17}/></button></div><dl>{[['PostgreSQL',health?.database?'Connected':'Unavailable'],['Transcript index',`${health?.episodes||0} episodes · ${health?.chunks||0} passages`],['Gemini',health?.gemini_configured?'Configured':'Not configured'],['Pi agent',health?.agent?'Connected':'Unavailable'],['Search',health?.embedding_model_ready?'Ready':'Unavailable']].map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v}</dd></React.Fragment>)}</dl><p>This public workspace uses Gemini and the hosted transcript index. Check the connection details above if a service is unavailable.</p></section>}
   <div className="chat-scroll" ref={scroll} onScroll={()=>{const e=scroll.current;if(e)follow.current=e.scrollHeight-e.scrollTop-e.clientHeight<100}}>
    {messages.length===0?<section className="welcome"><div className="eyebrow"><span/> THE LENNY GROWTH ASSISTANT</div><h1>Great advice.<br/><em>Your next move.</em></h1><p className="intro">Turn the best minds in product and growth into<br className="desktop-break"/> a clear path forward. Grounded in Lenny’s Podcast.</p><div className="starter-grid">{starters.map(({tag,q,icon:Icon})=><button className="starter" key={tag} onClick={()=>send(q)} disabled={busy}><Icon size={21}/><span className="starter-tag">{tag}</span><strong>{q}</strong><ArrowUpRight className="starter-arrow" size={18}/></button>)}</div><div className="archive-caption"><span className="tiny-lines">▥</span>{health?.episodes?`${health.episodes} episodes indexed`:'Your podcast research workspace'}<span>·</span>Sources you can trace. Ideas you can use.</div></section>:<div className="messages">{messages.map(m=><article key={m.id} className={'message '+m.role}><div className="message-label">{m.role==='assistant'?<><span className="assistant-mark">✳</span> LENNY <span className="message-model">{m.provider==='anthropic'?'Claude':m.provider==='gemini'?'Gemini':'Ollama'}</span></>:<>YOU</>}</div>{m.content?<Markdown text={m.content}/>:<div className="thinking"><span/><span/><span/></div>}{m.status==='failed'&&<div className="failed-label">Incomplete response</div>}{m.sources?.length>0&&<SourceCards sources={m.sources}/>} {artifacts.filter(a=>a.message_id===m.id).map(a=><button className="artifact-card" key={a.id} onClick={()=>{setArtifact(a);setView('preview')}}><FileText size={19}/><span>{a.title}<small>{a.artifact_type.toUpperCase()} · Open artifact</small></span><ArrowUpRight size={16}/></button>)}</article>)}<div ref={end}/></div>}
   </div>
   <div className="composer-area">{error&&<div role="alert" className="notice error">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={15}/></button></div>}{warning&&<div className="notice warning">{warning}</div>}{busy&&<div className="live-status" role="status"><span className="pulse"/>{status}</div>}
    <form className="composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea ref={inputRef} aria-label="Ask a product or growth question" placeholder="What are you working through?" value={input} maxLength={8000} disabled={busy} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}}/><div className="composer-bottom"><div className="mode-tabs">{[['answer','Ask',MessageSquare],['essay','Write an essay',Sparkles],['markdown','Document',FileText],['html','HTML',Code2]].map(([value,label,Icon])=>{const I=Icon as typeof MessageSquare;return <button type="button" key={String(value)} className={mode===value?'active':''} aria-pressed={mode===value} disabled={busy} onClick={()=>setMode(String(value))}><I size={14}/>{String(label)}</button>})}</div>{busy?<button type="button" className="send" aria-label="Stop generation" onClick={()=>abort.current?.abort()}><Square size={16}/></button>:<button className="send" aria-label="Send question" disabled={!input.trim()}><ArrowUp size={20}/></button>}</div></form>
    <div className="composer-note"><ShieldCheck size={12}/>{provider==='ollama'?'Local inference. Your questions stay on this machine.':provider==='gemini'?'Cloud mode. Retrieved excerpts and conversation context are sent to Google Gemini.':'Cloud mode. Retrieved excerpts and conversation context are sent to Anthropic.'}<span>Verify important claims.</span></div>
   </div>
  </main>
  {artifact&&<aside className="artifact-pane"><header><div><span className="eyebrow">YOUR ARTIFACT</span><h2>{artifact.title}</h2></div><button className="icon-button" aria-label="Close artifact" onClick={()=>setArtifact(null)}><PanelRightClose size={19}/></button></header><div className="artifact-toolbar"><div><button className={view==='preview'?'active':''} onClick={()=>setView('preview')}>Preview</button><button className={view==='source'?'active':''} onClick={()=>setView('source')}>Source</button></div><button className="icon-button" aria-label="Download artifact" onClick={download}><Download size={17}/></button></div><div className="artifact-content">{view==='source'?<pre>{artifact.content}</pre>:artifact.artifact_type==='html'?<iframe title="Isolated HTML artifact preview" sandbox="" referrerPolicy="no-referrer" srcDoc={safeDocument(artifact.content)}/>:<Markdown text={artifact.content}/>}</div><footer><Check size={13}/>{artifact.artifact_type==='html'?'Isolated static preview · Scripts blocked':`${words.toLocaleString()} words · Markdown document`}</footer></aside>}
 </div>
}
function AuthScreen({onAuthenticated}:{onAuthenticated:(user:User)=>void}){
 const [signup,setSignup]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{access_token:string;user:User}>(signup?'/auth/signup':'/auth/login',{method:'POST',body:JSON.stringify(signup?{name,email,password}:{email,password})});setAccessToken(result.access_token);onAuthenticated(result.user)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-card"><a className="brand" href="#"><span className="brand-mark">L<span>✳</span></span><span>Lenny<span className="brand-sub">GROWTH ASSISTANT</span></span></a><p className="auth-kicker">YOUR PRIVATE RESEARCH WORKSPACE</p><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Save grounded growth research in your own private workspace.':'Sign in to continue your product and growth research.'}</p><form onSubmit={submit}>{signup&&<label>Name<input required value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={signup?12:1} autoComplete={signup?'new-password':'current-password'}/>{signup&&<small>Use at least 12 characters.</small>}</label>{error&&<div role="alert" className="notice error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form><button className="auth-switch" onClick={()=>{setSignup(!signup);setError('')}}>{signup?'Already have an account? Sign in':'New here? Create an account'}</button></section></main>
}
function AdminPanel(){const [open,setOpen]=useState(false),[users,setUsers]=useState<AdminUser[]>([]),[error,setError]=useState('');async function show(){setOpen(true);try{setUsers(await api<AdminUser[]>('/admin/users'))}catch(e){setError((e as Error).message)}}return <><button className="admin-button" onClick={show}><Users size={14}/> Users</button>{open&&<section className="admin-panel"><div><strong>Registered users</strong><button className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div>{error?<p>{error}</p>:<table><thead><tr><th>Name</th><th>Email</th><th>Conversations</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}{u.is_admin&&<small>Admin</small>}</td><td>{u.email}</td><td>{u.conversation_count}</td></tr>)}</tbody></table>}</section>}</>}
function App(){const [user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true);useEffect(()=>{if(!accessToken()){setChecking(false);return}api<User>('/auth/me').then(setUser).catch(clearAccessToken).finally(()=>setChecking(false))},[]);async function logout(){try{await api('/auth/logout',{method:'POST'})}catch{}clearAccessToken();localStorage.removeItem('lenny-session');setUser(null)}if(checking)return <main className="auth-page">Loading your workspace…</main>;return user?<Workspace user={user} onLogout={logout}/>:<AuthScreen onAuthenticated={setUser}/>}
createRoot(document.getElementById('root')!).render(<App/>);
